In [1]:
import numpy as np

## Datatypes and Attributes

### Functions & Methods:
  * `type(array)`
  * `array.dtype`
  * `array.ndim`
  * `array.size`
  * `array.shape`

In [3]:
# Numpy's main datatype is ndarray

a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1,2.2,3.4],
               [4,5.6,6.3]])

a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [7]:
a2

array([[1. , 2.2, 3.4],
       [4. , 5.6, 6.3]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
 a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
# ndim - returns no. of dimensions
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [14]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [16]:
a1.size, a2.size, a3.size # returns the no. of elements in array

(3, 6, 18)

In [17]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [19]:
# Create a pandas dataframe using numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.2  3.4
1  4.0  5.6  6.3

In [20]:
type(a2), type(df)

(numpy.ndarray, pandas.core.frame.DataFrame)

In [21]:
# Machine learning is finding patterns in numpy array

## Creating arrays

### Different ways of creating arrays:

  * `np.ones()`
  * `np.zeros()`
  * `np.arange()`
  * `np.random.randint()`
  * `np.random.random()`
  * `np.random.rand()`

In [22]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [23]:
sample_array.dtype

dtype('int32')

In [24]:
type(sample_array)

numpy.ndarray

In [25]:
sample_array.ndim

1

In [26]:
sample_array.size

3

In [28]:
ones = np.ones((3,2), dtype='int')
ones

array([[1, 1],
       [1, 1],
       [1, 1]])

In [29]:
type(ones)

numpy.ndarray

In [30]:
ones.shape

(3, 2)

In [31]:
ones.size

6

In [32]:
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
type(zeros), zeros.dtype, zeros.ndim, zeros.size, zeros.shape

(numpy.ndarray, dtype('float64'), 2, 9, (3, 3))

In [35]:
range_array = np.arange(3,10,2)
range_array

array([3, 5, 7, 9])

In [36]:
random_array = np.random.randint(1,10,(3,2))
random_array

array([[8, 2],
       [2, 8],
       [5, 4]])

In [39]:
random_array_2 = np.random.random((3,4))
random_array_2

array([[0.52874048, 0.91244888, 0.05153145, 0.01021226],
       [0.02971715, 0.28080423, 0.15364936, 0.15354839],
       [0.54728051, 0.02674855, 0.76529336, 0.76037721]])

In [42]:
random_array_3 = np.random.rand(3,4,1)
random_array_3

array([[[0.51799779],
        [0.74359811],
        [0.33949682],
        [0.21721878]],

       [[0.75573499],
        [0.73405493],
        [0.09893441],
        [0.34688503]],

       [[0.62515474],
        [0.32343457],
        [0.06330469],
        [0.5623307 ]]])

In [58]:
# numpy generates Pseudo random numbers
np.random.seed(0)  # allows to generate reproducible random numbers

random_array_4 = np.random.randint(10,size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [52]:
random_array_4.shape

(5, 3)

## Viewing arrays and matrices

### Ways to view arrays and matrices:
  * `np.unique(array)`

In [59]:
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [61]:
np.unique(random_array_4,return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1, 1, 1, 3, 1, 2, 1, 2, 2, 1], dtype=int64))

In [64]:
a1

array([1, 2, 3])

In [65]:
a2

array([[1. , 2.2, 3.4],
       [4. , 5.6, 6.3]])

In [66]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [67]:
a1[0]

1

In [68]:
a2[0]

array([1. , 2.2, 3.4])

In [69]:
a3.shape

(2, 3, 3)

In [70]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [71]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
a3[0,1]

array([4, 5, 6])

In [77]:
a3[0,1,2]

6

In [75]:
# slicing numpy arrays
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [81]:
np.random.seed(0)
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[5, 0, 3, 3, 7],
         [9, 3, 5, 2, 4],
         [7, 6, 8, 8, 1],
         [6, 7, 7, 8, 1]],

        [[5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3],
         [3, 3, 7, 0, 1]],

        [[9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6],
         [8, 4, 1, 4, 9]]],


       [[[8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4],
         [4, 6, 4, 4, 3]],

        [[4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5],
         [0, 1, 2, 4, 2]],

        [[0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3],
         [2, 3, 4, 1, 2]]]])

In [79]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [82]:
a4[1,1,0,:4]

array([4, 4, 8, 4])

## Manipulating and comparing arrays

  ### Arithmetic
  
  * arr1 `+` arr2
  * arr1 `-` arr2
  * arr1 `*` arr2
  * arr1 `/` arr2
  * arr1 `//` arr2
  * arr1 `%` 2
  
  
  * `np.mod(arr1)`
  * `np.square(arr1)`
  * `np.add(arr1, arr2)`
  * `np.exp(arr1)`
  * `np.log(arr1)`

In [83]:
a1

array([1, 2, 3])

In [85]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [86]:
ones.shape

(3,)

In [87]:
a1+ones

array([2., 3., 4.])

In [88]:
a1 - ones

array([0., 1., 2.])

In [89]:
a1 * ones

array([1., 2., 3.])

In [93]:
a1

array([1, 2, 3])

In [90]:
a2

array([[1. , 2.2, 3.4],
       [4. , 5.6, 6.3]])

In [91]:
a1.shape , a2.shape

((3,), (2, 3))

In [92]:
a1 * a2

array([[ 1. ,  4.4, 10.2],
       [ 4. , 11.2, 18.9]])

In [94]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [95]:
# a2 * a3    # numpy broadcasting

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [96]:
# How can you reshape a2 to be compatible with a3? 
# Search "How to reshape numpy arrays?"

In [97]:
a1/ ones

array([1., 2., 3.])

In [98]:
a2

array([[1. , 2.2, 3.4],
       [4. , 5.6, 6.3]])

In [99]:
a1

array([1, 2, 3])

In [101]:
a2/a1

array([[1.        , 1.1       , 1.13333333],
       [4.        , 2.8       , 2.1       ]])

In [103]:
# Floor division removes the decimals (rounds down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [104]:
a2 ** 2

array([[ 1.  ,  4.84, 11.56],
       [16.  , 31.36, 39.69]])

In [105]:
np.square(a2)

array([[ 1.  ,  4.84, 11.56],
       [16.  , 31.36, 39.69]])

In [107]:
np.add(a1, ones)

array([2., 3., 4.])

In [109]:
a1 /2

array([0.5, 1. , 1.5])

In [108]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [112]:
np.mod(a1,2) # modulo

array([1, 0, 1], dtype=int32)

In [113]:
a2 % 2

array([[1. , 0.2, 1.4],
       [0. , 1.6, 0.3]])

In [116]:
np.exp(a2)

array([[  2.71828183,   9.0250135 ,  29.96410005],
       [ 54.59815003, 270.42640743, 544.57191013]])

In [117]:
np.log(a2)

array([[0.        , 0.78845736, 1.22377543],
       [1.38629436, 1.7227666 , 1.84054963]])