# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()

x1 = np.array([1,2,3,4])

# Create a 2-dimensional NumPy array using np.array()
x2= np.array([[1,2,3],
              [4,5,6]])

# Create a 3-dimensional Numpy array using np.array()

x3 = np.array([[[1.3,4.5,6.7],
                [5,6,7],
                [8,9,1]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [7]:
x1

array([1, 2, 3, 4])

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
x1.shape, x1.size, x1.ndim, x1.dtype, type(x1)

((4,), 4, 1, dtype('int32'), numpy.ndarray)

In [8]:
x2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# Attributes of 2-dimensional array
x2.shape, x2.size, x2.ndim, x2.dtype, type(x2)

((2, 3), 6, 2, dtype('int32'), numpy.ndarray)

In [6]:
x3

array([[[1.3, 4.5, 6.7],
        [5. , 6. , 7. ],
        [8. , 9. , 1. ]]])

In [5]:
# Attributes of 3-dimensional array
x3.shape, x3.size, x3.ndim, x3.dtype, type(x3)

((1, 3, 3), 9, 3, dtype('float64'), numpy.ndarray)

In [12]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(x2)
df

0  1  2
0  1  2  3
1  4  5  6

In [13]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [15]:
# Create an array within a range of 0 and 100 with step 3
x4 = np.arange(0,100,3)

In [16]:
x4

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [17]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
x5 = np.random.randint(0,10,size=(7,2))

In [18]:
x5

array([[1, 5],
       [4, 9],
       [7, 4],
       [3, 9],
       [6, 3],
       [5, 2],
       [6, 2]])

In [19]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
x6 = np.random.random((3,5))
x6

array([[0.08565872, 0.04647159, 0.07489841, 0.62638751, 0.07210032],
       [0.88883078, 0.37165222, 0.43931021, 0.66497195, 0.55350542],
       [0.32560514, 0.04926572, 0.24704766, 0.60492622, 0.10428348]])

In [22]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)

x7 = np.random.randint(0,10,size=(4,6))
x7

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [23]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
np.random.seed(42)
x8 = np.random.randint(1,10,size=(3,7))

# Find the unique numbers in the array you just created
np.unique(x8)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
x8

array([[7, 4, 8, 5, 7, 3, 7],
       [8, 5, 4, 8, 8, 3, 6],
       [5, 2, 8, 6, 2, 5, 1]])

In [26]:
# Find the 0'th index of the latest array you created
x8[0][0]

7

In [28]:
# Get the first 2 rows of latest array you created
x8[:2]

array([[7, 4, 8, 5, 7, 3, 7],
       [8, 5, 4, 8, 8, 3, 6]])

In [30]:
# Get the first 2 values of the first 2 rows of the latest array
x8[:2,:2]

array([[7, 4],
       [8, 5]])

In [33]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables

x9 = np.random.randint(0,10,size=(3,5))
x10 = np.ones((3,5))

In [37]:
x9

array([[6, 1, 3, 8, 1],
       [9, 8, 9, 4, 1],
       [3, 6, 7, 2, 0]])

In [38]:
x10

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
# Add the two arrays together
x9+x10

array([[ 7.,  2.,  4.,  9.,  2.],
       [10.,  9., 10.,  5.,  2.],
       [ 4.,  7.,  8.,  3.,  1.]])

In [39]:
# Create another array of ones of shape (5, 3)
x11 = np.ones((5,3))

In [42]:
# Try add the array of ones and the other most recent array together
x10 + x11

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [44]:
# Fixing by transposing one of the array to make them of same shape
x10 + x11.T

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [45]:
# Create another array of ones of shape (3, 5)
x12 = np.ones((3,5))

In [48]:
# Subtract the new array of ones from the other most recent array
x12 - x11.T

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
x12

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
x9

array([[6, 1, 3, 8, 1],
       [9, 8, 9, 4, 1],
       [3, 6, 7, 2, 0]])

In [51]:
# Do the same thing with np.square()
np.square(x9)

array([[36,  1,  9, 64,  1],
       [81, 64, 81, 16,  1],
       [ 9, 36, 49,  4,  0]], dtype=int32)

In [52]:
# Find the mean of the latest array using np.mean()
np.mean(np.square(x9))

30.133333333333333

In [53]:
# Find the maximum of the latest array using np.max()
np.max(x9)

9

In [54]:
# Find the minimum of the latest array using np.min()
np.min(x9)

0

In [55]:
# Find the standard deviation of the latest array
np.std(x9)

3.095516470998373

In [56]:
# Find the variance of the latest array
np.var(x9)

9.58222222222222

In [57]:
x9

array([[6, 1, 3, 8, 1],
       [9, 8, 9, 4, 1],
       [3, 6, 7, 2, 0]])

In [58]:
x9.shape

(3, 5)

In [60]:
# Reshape the latest array to (3, 5, 1)
x13 = x9.reshape(3,5,1)

In [61]:
x13

array([[[6],
        [1],
        [3],
        [8],
        [1]],

       [[9],
        [8],
        [9],
        [4],
        [1]],

       [[3],
        [6],
        [7],
        [2],
        [0]]])

In [62]:
x13.shape

(3, 5, 1)

In [63]:
# Transpose the latest array
x13.T

array([[[6, 9, 3],
        [1, 8, 6],
        [3, 9, 7],
        [8, 4, 2],
        [1, 1, 0]]])

In [64]:
x13.T.shape

(1, 5, 3)

What does the transpose do?

In [65]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
x14 = np.random.randint(0,10,size=(3,3))
x15 = np.random.randint(0,10,size=(3,2))

In [68]:
x14.shape, x15.shape

((3, 3), (3, 2))

In [67]:
# Perform a dot product on the two newest arrays you created
x16 = np.dot(x14,x15)
x16

array([[ 87,  25],
       [ 69,  19],
       [133,  23]])

In [69]:
x16.shape

(3, 2)

In [71]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
a1 = np.random.randint(0,10,size=(4,3))
a2 = np.random.randint(0,10,size=(4,3))

In [72]:
a1.shape, a2.shape

((4, 3), (4, 3))

In [73]:
# Perform a dot product on the two newest arrays you created
np.dot(a1, a2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [74]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(a1, a2.T)

array([[ 96, 166, 152,  56],
       [ 63,  98,  91,  49],
       [  8,  60,  58,   7],
       [ 26,  76,  72,  19]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [75]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a1 = np.random.randint(0,10,size=(4,3))
a2 = np.random.randint(0,10,size=(4,3))

In [77]:
a1

array([[6, 7, 4],
       [2, 7, 5],
       [2, 0, 2],
       [4, 2, 0]])

In [78]:
a2

array([[4, 9, 6],
       [6, 8, 9],
       [9, 2, 6],
       [0, 3, 3]])

In [76]:
# Compare the two arrays with '>'
a1>a2

array([[ True, False, False],
       [False, False, False],
       [False, False, False],
       [ True, False, False]])

What happens when you compare the arrays with `>`?

In [79]:
# Compare the two arrays with '>='
a1 >= a2

array([[ True, False, False],
       [False, False, False],
       [False, False, False],
       [ True, False, False]])

In [80]:
# Find which elements of the first array are greater than 7
a1>7

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [81]:
# Which parts of each array are equal? (try using '==')
a1 == a2

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [82]:
a1

array([[6, 7, 4],
       [2, 7, 5],
       [2, 0, 2],
       [4, 2, 0]])

In [83]:
# Sort one of the arrays you just created in ascending order
np.sort(a1)

array([[4, 6, 7],
       [2, 5, 7],
       [0, 2, 2],
       [0, 2, 4]])

In [85]:
# Sort the indexes of one of the arrays you just created
np.argsort(a1)

array([[2, 0, 1],
       [0, 2, 1],
       [1, 0, 2],
       [2, 1, 0]], dtype=int64)

In [88]:
a1

array([[6, 7, 4],
       [2, 7, 5],
       [2, 0, 2],
       [4, 2, 0]])

In [91]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a1)

1

In [92]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a1)

7

In [93]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(a1, axis=1)

array([1, 1, 0, 0], dtype=int64)

In [94]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(a1,axis=0)

array([1, 2, 3], dtype=int64)

In [99]:
# Create an array of normally distributed random numbers
a3 = np.random.normal(size =(2,3))

In [100]:
a3

array([[-0.50175704,  0.91540212,  0.32875111],
       [-0.5297602 ,  0.51326743,  0.09707755]])

In [101]:
# Create an array with 10 evenly spaced numbers between 1 and 100
a4 = np.linspace(1,100)
a4

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.